version: "3"
services:
  api:
    image: node:14.17.2
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=scores-admin
    volumes:
      - "./dbmigrations:/docker-entrypoint-initdb.d/:ro"
